### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shubhamR1997** [Cuadrix/puppeteer-page-proxy#23]
Not working with current latest pupeeter version. Does it support for pupeeter extra too?

**Comment by captchaharvest** [comment]
I'm getting this error too. Browser fails to load anything and then times out. I'm on version 3.3.0. Let me know if I can be of anymore help. Thanks!

**Comment by shubhamR1997** [comment]
Hey @captchaharvest . I have created a pull request for the fix of request based proxy. You can try that. I am working on replacing GOT with axios for more wider support. Since most of the sites are easily block in GOT cases. Will let you know when that version of this library is completed. Meanwhile you can try the pull request version until it get merged with master.

**Comment by DaMavius** [comment]
> Hey @captchaharvest . I have created a pull request for the fix of request based proxy. You can try that. I am working on replacing GOT with axios for more wider support. Since most of the sites are easily block in GOT cases. Will let you know when that version of this library is completed. Meanwhile you can try the pull request version until it get merged with master.

Hi, I have tried both current version and your pull with puppeteer 1.17.0 and 3.1.0. All of these combinationsl have the timeout problem. Nothing loads and timesout. I am using proxy with authentication and tried it without this module and it works. Really like the flexibility this module provides!

**Comment by Cuadrix** [comment]
Sorry for the delay guys. I haven't had time for this lately.
I'll update the module asap.

@shubhamR1997 As long as puppeteer-extra doesn't patch the page or request object, it should work, although I haven't tested it.

Before experimenting with Got I made an unreleased axios version. I haven't tested too much with it, but it seems that it worked and "errored" similarly to Got. In the end I chose to go with Got because of it's internal cookie support and easier implementation of the proxy agents.

Let me know what you come up with though, would be nice to have someone else maintaining this aswell.

@DaMavius Could be an issue with the proxy itself, or how Got handles the proxied request.
Have you tried more than one proxy?
What kind of proxies have you tried?
Http? Https? Socks?

**Comment by DaMavius** [comment]
> Sorry for the delay guys. I haven't had time for this lately.
> I'll update the module asap.
> 
> @shubhamR1997 As long as puppeteer-extra doesn't patch the page or request object, it should work, although I haven't tested it.
> 
> Before experimenting with Got I made an unreleased axios version. I haven't tested too much with it, but it seems that it worked and "errored" similarly to Got. In the end I chose to go with Got because of it's internal cookie support and easier implementation of the proxy agents.
> 
> Let me know what you come up with though, would be nice to have someone else maintaining this aswell.
> 
> @DaMavius Could be an issue with the proxy itself, or how Got handles the proxied request.
> Have you tried more than one proxy?
> What kind of proxies have you tried?
> Http? Https? Socks?

thanks for the quick reply, and you are right. It was due to the proxy I was using. I have made successful requests through proxy with puppeteer-page-proxy 1.2.5 and puppeteer 1.17.0.

**Comment by Cuadrix** [comment]
Updated. Try [1.2.6](https://github.com/Cuadrix/puppeteer-page-proxy/releases/tag/1.2.6)

**Comment by captchaharvest** [comment]
Works like a charm! Thanks for the update. It's a great module - keep up the awesome work.
