### ISSUE TITLE
Proxy Socks5 TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by kornflex** [Cuadrix/puppeteer-page-proxy#28]
Hello,

I have a proxy socks5 with authentication.

I'm trying to use it, so I wrote this : 

```
const puppeteer = require('puppeteer-extra');
const useProxy = require('puppeteer-page-proxy');
....
....
const browser = await puppeteer.launch(options);

const page = await browser.newPage();

await useProxy(page, 'socks://USER:PASSWMORD@proxy-nl.privateinternetaccess.com:1080');

...
...
```

When I launch the script, I have : TypeError: Cannot read property 'get' of undefined
This error happens with the line : 
await useProxy(page, 'socks://USER:PASSWMORD@proxy-nl.privateinternetaccess.com:1080');

Could you please help me ?

Thanks

**Comment by Cuadrix** [comment]
Hey. I'm unable to reproduce the issue, so I'll need more info.
Which version of this module and Nodejs are you using?

**Comment by kornflex** [comment]
Thank you for your help.

node version : 13.6.0
puppeteer-page-proxy 1.2.7 - 2020-06-30

The log : 

```
TypeError: Cannot read property 'get' of undefined
    at removeRequestListener (/var/www/clients/client1/web13/web/node_modules/puppeteer-page-proxy/src/core/proxy.js:44:38)
    at proxyPerPage (/var/www/clients/client1/web13/web/node_modules/puppeteer-page-proxy/src/core/proxy.js:76:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async useProxy (/var/www/clients/client1/web13/web/node_modules/puppeteer-page-proxy/src/core/proxy.js:90:9)
    at async /var/www/clients/client1/web13/web/scrapeProxySocksPIA.js:56:3
```

**Comment by Cuadrix** [comment]
Your line is fine.
Seem like you are using an old version of Puppeteer. Puppeteer did breaking changes in v4.0.0, which had to be taken into account in this module aswell because it was using one of the methods that was removed.
https://github.com/puppeteer/puppeteer/releases/tag/v4.0.0

In other words, this module currently only works with puppeteer v4.0.0+ and puppeteer-extra that is compatible with it.
Try updating your Puppeteer or Puppeteer-extra.

**Comment by kornflex** [comment]
Thank you very much !
That's it !
I succeed with your help !
