### ISSUE TITLE
Not working with puppeteer-extra-plugin-stealth

### ISSUE THREAD

**Issue by iners-max** [Cuadrix/puppeteer-page-proxy#71]
After I have added `puppeteer-page-proxy` to my web crawler, it stops working.

**Comment by jrejaud** [comment]
@Cuadrix I assume that you closed this issue because:

"Forwards intercepted requests from the browser to Node.js where it redoes the requests through a proxy and then returns the response to the browser."

So since requests are being done through Node rather than a browser, the browser obfuscation techniques using puppeteer-extra-plugin-stealth can't be used with puppeteer-page-proxy?
